name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
#      - run: npm test

      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: BUILD with number ${{env.build_version}} FAILED!
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.DISCORD_FAILED_BUILDS_WEBHOOK }}

      - name: Build passed
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Build ${{env.build_version}} successfully PASSED!
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          webhookUrl: ${{ secrets.DISCORD_PASSED_BUILDS_WEBHOOK }}